### PR TITLE
Feature/fix warnings in csv export

### PR DESCRIPTION
**Pull request by tfelix**

### CODE REVIEW

**Comment by Jelledb** [comment]
@tfelix This doesn't work. I still receive warnings in my CSV file.

I ran `collie tenant costs --from 2021-01-01 --to 2021-01-31 -o csv > test.csv`
and the CSV starts with the following content:

```
[34mINFO It seems you have not configured a Azure Management Group for Subscription lookup. Because of a bug in the Azure API, Collie can not detect this automatically. By configuring an Azure management group, cost & usage information lookups are significantly faster. Run 'collie config azure -h' for more information.[39m
[33mWARNING This CLI does not support GCP cost collection at the moment. We will implement this at a later stage when GCP supports billing exports via CLI.[39m
platform,platformTenantName,platformTenantId,from,to,totalCost,currency,ms-resource-usage,SecurityContact,customerIdentifier,projectIdentifier,test,meshstack_pident,meshstack_cident,meshstack_confidentiality,costCenter,tagCostCenter,mesh-customer,mesh-project,meshstack_businessunit,meshstack_environment,meshstack_costcenter,meshstack_my_special_tag,meshstack_projectowner,meshstack_securitycontact,meshstack_testreplication,meshstack_costcenternumber
```


Make sure to clear your cache when you're testing this

**Review by Jelledb — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by tfelix** [comment]
Did you run collie? You non updated local binary or run.sh? Works for me. 
image

**Comment by Jelledb** [comment]
> Did you run collie? Was it your non updated local binary or run.sh? Because it seems to work for me.
> image

Yup, that was it 😓

**Review by Jelledb — APPROVED** [review]

**Pull request merged**
